import Image from "next/image";
import Link from "next/link";
import { ContactForm } from "./ContactForm";
import { PRESETS, Preset, site } from "@/lib/site";
const labels: Record<Preset,string> = { "luxury-editorial":"Luxury editorial", "neighbourhood-journal":"Neighbourhood journal", "modern-team":"Modern team" };
export function Site({ preset }: { preset: Preset }) {
  return <main className="site" data-preset={preset}>
    <a className="skip" href="#content">Skip to content</a>
    <header className="masthead">
      <Link href="#top" className="identity" aria-label={`${site.agent.name}, home`}><Image src={site.agent.logo} alt="" width={44} height={44}/><span><b>{site.agent.name}</b><small>{site.agent.title} · {site.agent.brokerage}</small></span></Link>
      <nav aria-label="Primary"><a href="#listings">Listings</a><a href="#about">About</a><a href="#services">Services</a><a href="#neighbourhoods">Neighbourhoods</a><a className="nav-cta" href="#contact">Let&apos;s talk</a></nav>
    </header>
    <section className="preset-switcher" aria-label="Preview design preset"><span>Design:</span>{PRESETS.map(p => <Link key={p} aria-current={p===preset ? "page":undefined} href={`/presets/${p}`}>{labels[p]}</Link>)}</section>
    <div id="content">
      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{site.copy.eyebrow}</p><h1>{site.copy.headline}</h1><p className="lede">{site.copy.introduction}</p><div className="actions"><a className="button" href="#contact">{site.copy.valuationCta}</a><a className="text-link" href="#listings">View featured examples <span aria-hidden="true">→</span></a></div></div><figure className="portrait"><Image src={site.agent.headshot} alt={`Portrait illustration of ${site.agent.name}`} width={700} height={860} priority/><figcaption>{site.agent.markets.join(" · ")}</figcaption></figure></section>
      <section className="listings section" id="listings"><header className="section-head"><p className="kicker">Selected homes</p><h2>Listings, presented with context.</h2><p>These are manually entered fictional examples for this starter—not live MLS®, IDX, or VOW data.</p></header><div className="listing-grid">{site.featuredListings.map((listing,index)=><article className="listing" key={listing.id}><div className="listing-image"><Image src={listing.image} alt={listing.alt} width={900} height={620}/><span>{listing.status}</span></div><div className="listing-copy"><p>{String(index+1).padStart(2,"0")} / {listing.city}</p><h3>{listing.address}</h3><div><b>{listing.price}</b><span>{listing.beds} beds · {listing.baths} baths</span></div><a href={listing.url}>Ask about this example <span aria-hidden="true">→</span></a></div></article>)}</div></section>
      <section className="about section" id="about"><div className="about-portrait"><Image src={site.agent.headshot} alt="" width={500} height={600}/></div><div><p className="kicker">About {site.agent.name.split(" ")[0]}</p><h2>Clear advice. Thoughtful representation.</h2><p>{site.agent.biography}</p><dl><div><dt>Brokerage</dt><dd>{site.agent.brokerage}</dd></div><div><dt>{site.agent.licenseLabel}</dt><dd>{site.agent.licenseNumber}</dd></div><div><dt>Markets</dt><dd>{site.agent.markets.join(", ")}</dd></div></dl></div></section>
      <section className="services section" id="services"><header className="section-head"><p className="kicker">How I can help</p><h2>A practical plan for the move in front of you.</h2></header><div className="service-list">{site.services.map((s,i)=><article key={s.title}><span>{String(i+1).padStart(2,"0")}</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></section>
      <section className="neighbourhoods section" id="neighbourhoods"><header className="section-head"><p className="kicker">Local field notes</p><h2>Start with how you want to live.</h2><p>Objective, housing-focused overviews—not demographic steering or a substitute for your own due diligence.</p></header><div className="neighbourhood-list">{site.neighbourhoods.map((n,i)=><article key={n.name}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{n.name}</h3><p>{n.summary}</p></div><a href={n.link} aria-label={`Ask about ${n.name}`}>Explore <span aria-hidden="true">↗</span></a></article>)}</div></section>
      {site.testimonials.length > 0 && <section className="quotes section" aria-label="Verified client testimonials">{site.testimonials.map(t=><blockquote key={t.quote}><p>“{t.quote}”</p><cite>{t.attribution}</cite></blockquote>)}</section>}
      {site.stats.length > 0 && <section className="stats section" aria-label="Verified business statistics">{site.stats.map(s=><div key={s.label}><b>{s.value}</b><span>{s.label}</span></div>)}</section>}
      <section className="contact section" id="contact"><div className="contact-copy"><p className="kicker">Begin with a conversation</p><h2>Tell me what a good next move looks like.</h2><p>Buying, preparing to sell, or simply sorting out timing? Share the outline and we&apos;ll decide whether a conversation would be useful.</p><address><a href={`mailto:${site.agent.email}`}>{site.agent.email}</a><a href={`tel:${site.agent.phone.replace(/[^+\d]/g,"")}`}>{site.agent.phone}</a><span>{site.agent.officeAddress}</span></address></div><ContactForm/></section>
      <aside className="apv-band" aria-label="Real estate media consultations"><div><p>Planning a listing launch?</p><h2>Show the property at its best.</h2><p>Contact Amazing Photo Video to ask about real estate photography and video for an upcoming listing. Availability and scope are confirmed during consultation.</p><a href={site.apv.mediaConsultationUrl}>Ask APV about listing media <span aria-hidden="true">→</span></a></div><div><p>Coordinate the media day</p><h2>Plan the right media mix.</h2><p>Discuss the property, timeline, and deliverables with APV before booking. No photography, video, or other service is implied until APV confirms it.</p><a href={site.apv.mediaPlanningUrl}>Request an APV media consultation <span aria-hidden="true">→</span></a></div></aside>
    </div>
    <footer><div><b>{site.agent.name}</b><span>{site.agent.title} · {site.agent.brokerage}</span><span>{site.agent.licenseLabel}: {site.agent.licenseNumber}</span></div><p>{site.consent.disclaimer}</p><a className="apv-credit" href="https://amazingphotovideo.com">{site.apv.footerLabel}</a></footer>
  </main>;
}
